### ISSUE TITLE
syntax error on lines 21, 23

### ISSUE THREAD

**Issue by rbalicki2** [paramaggarwal/multipart#1]
I'm getting the following:

```
./multipart.sh: line 21: *(1-1)/20: syntax error: operand expected (error token is "*(1-1)/20")
./multipart.sh: line 23: (*1/20)-1: syntax error: operand expected (error token is "*1/20)-1")
curl --silent --range - -o temp.part1 http://download.gimp.org/pub/gimp/v2.8/osx/gimp-2.8.14.dmg &
```

Any help would be appreciated! 

Edit: it appears the size is getting logged as an empty string.

**Comment by paramaggarwal** [comment]
Sorry haven't got time to look into this yet.

**Comment by nick-wellinghoff-sp** [comment]
This will happen if the url can't be resolved. e.g. size is = not set

**Comment by paramaggarwal** [comment]
I am using [aria2](https://aria2.github.io) now for multi-part downloads. Hence won't be looking into debugging issues on this project anymore.

**Comment by paramaggarwal** [comment]
@rbalicki2 Try running this command separately and see if it is able to pull out the size correctly

https://github.com/paramaggarwal/multipart/blob/c54cce53c6aace93b0da62ff8e9deeba94c13e11/multipart.sh#L14
